name: Build and Push Container

on:
  push:
    branches: 
      - main
      - development
  pull_request:
    branches: 
      - main
      - development
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch

      - name: Set version based on branch
        id: set_version
        run: |
          if [ "${{ env.BRANCH_NAME }}" = "main" ]; then
            echo "VERSION=v$(date +'%Y').$(date +'%-m')" >> $GITHUB_OUTPUT
          elif [ "${{ env.BRANCH_NAME }}" = "development" ]; then
            echo "VERSION=v$(date +'%Y').$(date +'%-m').$(date +'%-d')" >> $GITHUB_OUTPUT
          else
            echo "VERSION=${{ env.BRANCH_NAME }}-${{ steps.date.outputs.DATE }}" >> $GITHUB_OUTPUT
          fi

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.set_version.outputs.VERSION }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}